server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/produtos/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/pedidos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 